-- ============================================================
-- TCC FINAL — CONECTA VAGAS DF — DADOS DE DEMONSTRAÇÃO (seed)
-- ============================================================
-- Importe DEPOIS do database/schema.sql.
-- Contas de teste (troque as senhas antes de publicar):
--   admin@conectavagas.com     / Admin@123
--   empresa@conectavagas.com   / Empresa@123
--   candidato@conectavagas.com / Candidato@123
-- Inclui 20 categorias (13 de vagas, 7 de cursos), 62 vagas (cartazes em public/assets/img/vagas),
-- 64 conteúdos de capacitação (43 cursos e 21 e-books gratuitos, de fontes oficiais, cada um com a sua imagem)
-- e a assinatura VIP do candidato de teste.
-- ============================================================

SET NAMES utf8mb4;
USE tcc_final;

INSERT INTO usuarios(nome,email,senha,tipo,telefone) VALUES
('Administrador','admin@conectavagas.com','$2y$12$6AKJ6lx6.h0haWsmgiDBwe4fMaMjUTlKw5uhg/Qj7Y6mUVgEXrvfu','admin','(61) 99999-9999'),
('Empresa Teste','empresa@conectavagas.com','$2y$12$tzGJeKQV5zNrxYei.3hWeu48g3iywGTSY4Moyn8F/48TiP4/hZYhm','empresa','(61) 98888-8888'),
('Candidato Teste','candidato@conectavagas.com','$2y$12$AKmQPWZpUGx/xu7xB7vZgOdb8vSTl5/tfNuW8buI01Uaehs8APLaa','candidato','(61) 97777-7777');

INSERT INTO perfis(usuario_id,nome_fantasia,setor,cidade,uf,bio,publico,aceite_lgpd,aceite_em,titulo_profissional,nivel_experiencia,habilidades,competencias,objetivo) VALUES
(2,'Empresa Teste','Tecnologia','Brasília','DF','Empresa de teste do ambiente local.',1,1,NOW(),NULL,'junior',NULL,NULL,NULL),
(3,NULL,NULL,'Brasília','DF','Perfil de candidato para testes.',1,1,NOW(),'Candidato em busca de oportunidades','junior','Atendimento, Excel, Tecnologia','Comunicação, organização','Buscar oportunidade profissional no DF.');

INSERT INTO categorias(nome,tipo) VALUES
('Tecnologia da Informação','vaga'),('Administração','vaga'),('Marketing','vaga'),('Vendas','vaga'),('Recursos Humanos','vaga'),('Financeiro','vaga'),('Engenharia','vaga'),('Saúde','vaga'),('Educação','vaga'),
('Informática e Excel','curso'),('Empreendedorismo e Gestão','curso'),('Administração e Atendimento','curso'),('Marketing, Dados e UX','curso'),('Negócios, Finanças e ESG','curso'),
('Alimentação','vaga'),('Serviços Gerais e Limpeza','vaga'),('Logística e Transporte','vaga'),('Atendimento ao Público','vaga'),
('Tecnologia e Inteligência Artificial','curso'),('Carreira e Empregabilidade','curso');

SET @perfil_empresa_teste = (SELECT id FROM perfis WHERE usuario_id = 2);

INSERT INTO vagas(perfil_empresa_id,categoria_id,titulo,descricao,requisitos,beneficios,tipo_vaga,nivel_experiencia,remoto,cidade,uf,salario_minimo,salario_maximo,imagem,status,data_publicacao) VALUES
(@perfil_empresa_teste,4,'Atendente / Vendedor / Gerente','Oportunidade para atendimento e vendas em shoppings de Brasília e Aeroporto.','Comunicação, atendimento ao cliente e disponibilidade para escala 6x1.','Salário entre R$ 1.700 e R$ 2.400 + benefícios.','clt','junior','presencial','Brasília','DF',1700,2400,'assets/img/vagas/vaga1.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,8,'Técnico de Enfermagem','Atuação em centro médico no Guará.','Curso técnico e registro profissional conforme a função. Residir no Guará ou proximidades.','Salário compatível + VT.','clt','junior','presencial','Guará','DF',NULL,NULL,'assets/img/vagas/vaga2.png','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor Interno','Atendimento comercial e vendas internas em Taguatinga.','Comunicação, negociação e foco em resultados.','R$ 3.000 a R$ 5.500 + comissões. 10 vagas.','clt','junior','presencial','Taguatinga','DF',3000,5500,'assets/img/vagas/vaga3.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Atendente de Loja (6h)','Atendimento em loja em Águas Claras.','Disponibilidade para jornada de 6 horas.','R$ 1.105 + VT + academia + shake proteico.','clt','junior','presencial','Águas Claras','DF',1105,1105,'assets/img/vagas/vaga4.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,17,'Motorista','Entregas de hortifrúti com horários flexíveis.','CNH B ou D e disponibilidade para madrugada/manhã.','Horários flexíveis.','clt','junior','presencial','Brasília','DF',NULL,NULL,'assets/img/vagas/vaga5.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,16,'Empregada Doméstica','Atuação em residência em Vicente Pires.','Experiência com rotina doméstica e disponibilidade de segunda a sábado.','R$ 1.621 + VT + alimentação. 7h às 15h.','clt','junior','presencial','Vicente Pires','DF',1621,1621,'assets/img/vagas/vaga6.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,7,'Bombeiro Hidráulico (Obra)','Atuação em obra de grande porte.','Experiência em obras de grande porte.','R$ 2.420 + VT + VR R$ 33,40.','clt','pleno','presencial','Brasília','DF',2420,2420,'assets/img/vagas/vaga7.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,7,'Eletricista de Obra','Atuação em obra no Lago Sul.','Experiência em elétrica predial.','R$ 2.420 + VT + VR R$ 33,40. Segunda a sexta, 7h às 17h.','clt','pleno','presencial','Lago Sul','DF',2420,2420,'assets/img/vagas/vaga8.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Atendente McDonald’s','Atendimento em unidade de Águas Claras.','Disponibilidade para escala 5x2 ou 12x36.','Plano de saúde, odonto, day off e cesta básica.','clt','junior','presencial','Águas Claras','DF',NULL,NULL,'assets/img/vagas/vaga9.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,2,'Auxiliar Administrativo','Rotinas administrativas, organização de documentos, controle de planilhas e atendimento telefônico.','Pacote Office, Excel intermediário, boa comunicação e organização.','R$ 1.900 + VT + VR.','clt','junior','presencial','Brasília','DF',1900,1900,'assets/img/vagas/vaga11.png','ativa',CURDATE()),
(@perfil_empresa_teste,1,'Desenvolvedor PHP Júnior','Desenvolvimento e manutenção de sistemas web.','PHP, MySQL, HTML, CSS, JavaScript e Git.','R$ 3.500 a R$ 4.500 + VR + plano de saúde. Modelo híbrido.','clt','junior','hibrido','Brasília','DF',3500,4500,'assets/img/vagas/vaga10.png','ativa',CURDATE());


-- Vagas cadastradas a partir dos cartazes enviados (curadoria; anunciante = empresa do cartaz).
INSERT INTO vagas(perfil_empresa_id,categoria_id,titulo,anunciante,descricao,requisitos,beneficios,contato,tipo_vaga,nivel_experiencia,remoto,cidade,uf,salario_minimo,salario_maximo,imagem,status,data_publicacao) VALUES
(@perfil_empresa_teste,15,'Atendente / Garçom','Meire Gontijo','Meire Gontijo contrata atendente / garçom no Guará.',NULL,'Salário a combinar + comissão\nVale-alimentação no local\nVale-transporte\nPlano odontológico pelo sindicato\nProdutividade para quem não faltar','WhatsApp (61) 99324-2305','clt','junior','presencial','Guará','DF',NULL,NULL,'assets/img/vagas/vaga24.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Auxiliar de Cozinha','Restaurante Prosa di Minas','Auxiliar de cozinha no Restaurante Prosa di Minas, em Águas Claras. Horário das 8h às 16h, com 1 folga semanal.','Experiência na função\nComprometimento','Salário de R$ 1.859,00\nVale-transporte\nAlimentação no local\n1 folga semanal','WhatsApp (61) 98549-9498 · prosarh2020@gmail.com','clt','junior','presencial','Águas Claras','DF',1859.00,NULL,'assets/img/vagas/vaga25.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Operador de Cópias / Impressões','Papelaria Shalom','A Papelaria Shalom contrata 2 operadores de cópias e impressões no Guará II. Atividades: impressão, cópias, digitalização de documentos e encadernação.','Ensino médio completo\nConhecimento básico em Word e Excel','Salário comercial\nVale-transporte','WhatsApp (61) 99189-1238','clt','junior','presencial','Guará','DF',NULL,NULL,'assets/img/vagas/vaga26.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Churrasqueiro','Casa Gaúcha Restaurante e Churrascaria','1 vaga de churrasqueiro com experiência no SIA. Segunda a sábado, das 7h às 16h.','Experiência como churrasqueiro','Salário a combinar\nVale-transporte\nAlimentação','WhatsApp (61) 99909-9896','clt','pleno','presencial','SIA','DF',NULL,NULL,'assets/img/vagas/vaga27.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedora','Loja de Moda Feminina','Loja de moda feminina em Ceilândia Norte contrata vendedora para vendas e atendimento ao cliente.','Gostar de vendas e atendimento\nSer ágil, comunicativa e organizada\nDisponibilidade de horário',NULL,'WhatsApp (61) 98260-0618','clt','junior','presencial','Ceilândia','DF',NULL,NULL,'assets/img/vagas/vaga28.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Garçom / RH-DP / Operador de Caixa','Mandaka','O Mandaka contrata com início imediato: garçom, assistente de RH/DP e operador de caixa. Lojas em Taguatinga Sul, Águas Claras e Guará II.','Experiência na função\nResidir no DF\nDisponibilidade de horário','Salário + produtividade + gorjeta\nRefeição no local\nFiliação a clubes\nClínica médica e saúde mental\nPlano odontológico gratuito\nPlano de medicamentos','WhatsApp (61) 99350-6572 · vagastrabalho27@gmail.com','clt','junior','presencial','Taguatinga','DF',NULL,NULL,'assets/img/vagas/vaga29.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,2,'Estágio em Administração / RH','Restaurante Self-Service Asa Norte','Restaurante self-service na Asa Norte contrata estagiários de Administração, Recursos Humanos, Tecnólogos em Gestão e cursos afins. Horário das 10h às 16h, com folga fixa na semana ou escala ajustada ao curso.','Cursar Administração, RH, Tecnólogo em Gestão ou curso afim','Bolsa a partir de R$ 1.200,00 líquidos\nVale-transporte\nAlmoço no local\nSeguro de vida','WhatsApp (61) 99620-1679','estagio','estagiario','presencial','Asa Norte','DF',1200.00,NULL,'assets/img/vagas/vaga30.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Jovem Aprendiz — Posto de Combustíveis','Cascol','Jovem aprendiz para atuar em posto de combustíveis: atendimento ao público e apoio às rotinas operacionais do posto. Regiões: Taguatinga, Ceilândia, Guará, Paranoá, São Sebastião, Varjão, Sobradinho e Planaltina.','18 anos completos\nDisponibilidade para jornada de 6 horas',NULL,'WhatsApp (61) 98625-7024','clt','estagiario','presencial','Taguatinga','DF',NULL,NULL,'assets/img/vagas/vaga31.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Atendente','Subway (Grupo Elizete)','O Subway contrata atendente para as lojas de Taguatinga Sul, Ceilândia Norte e M Norte.','Ensino médio completo\nProatividade\nBoa comunicação\nVontade de aprender\nDisponibilidade de horário',NULL,'vagasgrupoelizete@gmail.com · WhatsApp (61) 98402-4592','clt','junior','presencial','Taguatinga','DF',NULL,NULL,'assets/img/vagas/vaga32.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor(a)','Alô Celulares','Vendas e atendimento ao cliente em loja de acessórios para celulares, capas, películas e produtos de informática no Shopping Conjunto Nacional. Escala 6x1, das 14h às 22h. No e-mail, informe \"Vendedor(a) Conjunto Nacional\".','Experiência com vendas será um diferencial','Salário de R$ 1.790,26\nBonificação por vendas\nVale-transporte','alocelulares.curriculos@gmail.com · Jéssica (61) 99839-0202','clt','junior','presencial','Brasília','DF',1790.26,NULL,'assets/img/vagas/vaga33.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Copeira','Casa do Vovô','A Casa do Vovô, em Vicente Pires, contrata copeira. Escala 12x36 (trabalha um dia e folga no outro); horas extras pagas quando realizadas.',NULL,'Salário bruto inicial de R$ 1.707,54\nVale-transporte\nCafé da manhã e lanche da tarde\nAlmoço: cesta básica mensal ou marmita diária\nParceria com a Anhanguera (descontos em graduação, extensivos aos familiares)','contato.rh.csv@gmail.com','clt','junior','presencial','Vicente Pires','DF',1707.54,NULL,'assets/img/vagas/vaga34.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,16,'Zelador / Encarregado de Serviços Gerais','Casa do Vovô','A Casa do Vovô, em Vicente Pires, contrata zelador / encarregado de serviços gerais. Segunda a sábado; horas extras pagas quando realizadas.','Curso de Agente de Limpeza','Salário a combinar\nVale-transporte\nCafé da manhã e lanche da tarde\nAlmoço: cesta básica mensal ou marmita diária\nParceria com a Anhanguera (descontos em graduação, extensivos aos familiares)','contato.rh.csv@gmail.com','clt','junior','presencial','Vicente Pires','DF',NULL,NULL,'assets/img/vagas/vaga35.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Atendente de Lanchonete','Giraffas','O Giraffas contrata atendente de lanchonete para o Shopping Boulevard, na Asa Norte. Escala 12x36, das 10h às 22h.',NULL,'Salário comercial\nVale-transporte\nAlimentação no local\nProdutividade','WhatsApp (61) 98473-6782','clt','junior','presencial','Asa Norte','DF',NULL,NULL,'assets/img/vagas/vaga36.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor(a) — Cenografia e Estandes','Empresa de Cenografia e Eventos','Empresa de cenografia, estandes, mobiliário, palcos, balcões de credenciamento e comunicação visual para feiras, congressos e eventos corporativos em Brasília. CLT (contrato de experiência), 44 horas semanais presenciais nas unidades do SAAN e do CICB, incluindo sábado pela manhã.','Prospecção e organização do funil de vendas\nAgilidade e foco em resultados','Salário fixo de R$ 2.500,00 + comissão sobre vendas, sem teto\nAuxílio-refeição de R$ 29,03 por dia útil (cerca de R$ 638/mês)\nVale-transporte\nSeguro de vida\nDemais benefícios da convenção coletiva','Ysadora — WhatsApp (21) 97492-4014','clt','junior','presencial','Brasília','DF',2500.00,NULL,'assets/img/vagas/vaga37.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Embaixador(a) da Experiência do Cliente','McDonald’s Asa Sul','Cuidar da jornada do cliente do início ao fim da visita, com atenção, respeito e o melhor atendimento. McDonald’s da quadra 404/405 da Asa Sul. Escala 6x1, das 16h às 00h. Ao enviar o currículo, informe que é para a vaga de Embaixador.','Maior de 18 anos\nFacilidade de acesso ao restaurante','Salário bruto de R$ 2.239,00\nPlano de saúde\nPlano odontológico\nSeguro de vida\nRefeição no local\nVale-transporte\nGympass\nBolsas de estudo\nPlano de carreira','WhatsApp (61) 99801-5842','clt','junior','presencial','Asa Sul','DF',2239.00,NULL,'assets/img/vagas/vaga38.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Auxiliar de Cozinha / Chapeiro / Garçom','A Banka','A Banka, no Cruzeiro Velho, contrata auxiliar de cozinha, chapeiro e garçom. Funções: apoio na cozinha, preparo e organização dos alimentos, limpeza e higienização, atendimento e suporte à equipe. Segunda a sábado, das 8h às 16h30, com folga todos os domingos.','Experiência na função\nMorar no DF\nComprometimento e pontualidade\nTrabalho em equipe','Salário base de R$ 1.750 a R$ 2.200, conforme a função\nVale-transporte\nVale-alimentação no local\nProdutividade\nComissão global','WhatsApp (61) 98201-7405','clt','junior','presencial','Cruzeiro','DF',1750.00,2200.00,'assets/img/vagas/vaga39.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,17,'Motorista de Caminhão','UAÇO','A UAÇO contrata motorista de caminhão no Setor de Indústria de Ceilândia.','CNH categoria C\nDisponibilidade para viagens','Salário acima da categoria\n10% de assiduidade\nVale-refeição\nCesta básica\nVale-transporte','curriculos.uacobrasil@gmail.com · WhatsApp (61) 99000-2115','clt','junior','presencial','Ceilândia','DF',NULL,NULL,'assets/img/vagas/vaga40.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,5,'Auxiliar / Assistente de DP-RH','Empresa privada em Santa Maria','Contratação para departamento pessoal, RH e parte fiscal (auxiliar, assistente ou analista), com início imediato. Atividades: rotinas de Departamento Pessoal e Recursos Humanos. Agende a entrevista com Estefâne pelo telefone.','Experiência em DP/RH\nConhecimento em legislação tributária e obrigações acessórias (PIS/COFINS, ICMS, ISS)\nDisponibilidade para início imediato','Salário de R$ 2.000,00\nVale-transporte (passagem até R$ 10,00)\nVale-alimentação de R$ 20,00','Estefâne — (61) 9904-3008','clt','pleno','presencial','Santa Maria','DF',2000.00,NULL,'assets/img/vagas/vaga41.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Consultor(a) de Vendas','Vivo — Parceiro 4R','Venda de serviços de telefonia e dados, esclarecimento de informações técnicas e suporte aos clientes na escolha da solução adequada, com atuação em sondagem, prospecção e pós-venda. Vaga em Águas Lindas (GO), também para PCD.','Ensino médio completo\nDisponibilidade de horário\nComunicação\nResponsabilidade\nFoco em resultados\nInteresse por tecnologia','Salário fixo de R$ 1.621,00\nVale-alimentação de R$ 20,00/dia\nVale-transporte\nComissão de vendas e premiações por meta\nSeguro de vida\nPlano de carreira\nPlano odontológico\nDescontos em farmácias\nCartão de benefícios\nTotalPass\nDay off\nTelemedicina','WhatsApp (61) 99698-1058','clt','junior','presencial','Águas Lindas','GO',1621.00,NULL,'assets/img/vagas/vaga42.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Estágios: Atendente, Vendas, Secretária(o) e Refrigeração','Zane Estágios','5 oportunidades de estágio em Brasília/DF:\n1. Atendente — Asa Norte — R$ 800 + VT + VA — seg. a sáb., 30h semanais\n2. Atendente de loja — Asa Norte — R$ 1.000 + comissão — seg. a sex.\n3. Atendimento e vendas — Gama Shopping — R$ 900 + comissão por metas — seg. a sáb., 5h diárias\n4. Secretária(o) — Cruzeiro — R$ 900 + VT — seg. a sáb., 9h às 15h\n5. Auxiliar de refrigeração — Cruzeiro — R$ 900 + VT — seg. a sex. 9h–15h, sáb. 8h–12h','Estar estudando (vaga de estágio)\nAuxiliar de refrigeração: noções básicas de refrigeração','Bolsa de R$ 800 a R$ 1.000\nVale-transporte (conforme a vaga)\nComissão nas vagas de loja e vendas','WhatsApp (61) 99318-0769','estagio','estagiario','presencial','Asa Norte','DF',800.00,1000.00,'assets/img/vagas/vaga43.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Trainee de Vendas','JOVI','7 vagas de trainee de vendas, CLT, em Brasília/DF. Responsabilidades: apoiar vendas, atender clientes, prospectar oportunidades, apoiar propostas e negociações, acompanhar metas e indicadores e participar de treinamentos e projetos. No e-mail, use o título \"Trainee de Vendas\".','Inglês fluente/avançado (conversação e escrita) — obrigatório\nGraduação completa em qualquer área\nRecém-formado(a)\nPacote Office intermediário\nPerfil proativo e vontade de aprender','Salário de R$ 2.200,00\nVale-alimentação de R$ 40,00 por dia\nCartão mobilidade de R$ 400,00\nPlano de saúde e odontológico Bradesco\nSeguro de vida','mwhr@jovimobile.com · (61) 98175-0661','clt','junior','presencial','Brasília','DF',2200.00,NULL,'assets/img/vagas/vaga44.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Atendente','Panificadora Gonçalina','A Panificadora Gonçalina contrata atendente. Vagas para o SIA e Ceilândia. Deixe o currículo na loja ou envie por e-mail.',NULL,'Regime CLT\nVale-transporte\nSalário e horário a combinar','goncalinarh@gmail.com · (61) 99404-2674','clt','junior','presencial','Ceilândia','DF',NULL,NULL,'assets/img/vagas/vaga45.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Diversas vagas: Operador de Loja, Auxiliares e Estagiários','Cinco Estrelas Casa de Pães','A Cinco Estrelas Casa de Pães, com mais de 30 anos de mercado, tem vagas em aberto: Nutricionista (1), Auxiliar de Cozinha (1), Auxiliar de Produção (2), Estagiário de Nutrição (2), Estagiário de Produção (5), Estagiário de Loja (10), Estagiário de RH (1), Auxiliar de Serviços Gerais (1), Operador de Loja (10) e Motoboy (1). Unidades: Ceilândia (Setor O), Guará I e II, Asa Sul, Sudoeste, Noroeste e Águas Claras. Envie o currículo com o cargo pretendido. Todas as vagas são abertas para PCD.',NULL,'Alimentação no local (Setor O) ou vale-alimentação (operador de loja 12x36)\nVale-transporte com crédito quinzenal\nVenda a prazo: 10% do salário em produtos da loja + 5% de desconto\nDay off no mês do aniversário\nParcerias com faculdades\nPlano de saúde PRIME-X: R$ 49,90 para toda a família\nOportunidades de crescimento interno','rh.cecp@gmail.com · (61) 98626-0256','clt','junior','presencial','Ceilândia','DF',NULL,NULL,'assets/img/vagas/vaga46.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Auxiliar de Cozinha','Grupo Dourado','Auxiliar de cozinha em Águas Claras, 2 vagas. Das 14h20 às 22h, CLT 6x1.',NULL,'Salário a partir de R$ 1.900,00\nVale-transporte\nAlimentação no local\nPremiação mensal\nTreinamento especializado','grupodouradooo@gmail.com · (11) 98855-1331','clt','junior','presencial','Águas Claras','DF',1900.00,NULL,'assets/img/vagas/vaga47.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor(a)','World Tennis','A World Tennis contrata vendedor(a) para as lojas do Taguatinga Shopping, JK Shopping, Park Shopping, Conjunto Nacional, Pátio Brasil e Shopping Sul.',NULL,NULL,'curriculowt@gmail.com · WhatsApp (61) 99886-5320','clt','junior','presencial','Brasília','DF',NULL,NULL,'assets/img/vagas/vaga48.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,16,'Diarista','Tô Mais Vip Diaristas','30 vagas de diarista com trabalho fixo e pagamento todo dia 15. Ganho inicial de R$ 2.611,00/mês (R$ 2.369,00 de pagamento + R$ 242,00 de transporte).',NULL,'Pagamento mensal de R$ 2.369,00 (todo dia 15)\nTransporte de R$ 242,00/mês (R$ 11,00/dia, Cartão BRB Mobilidade)\nPremiação anual\nPremiações extras (Dia da Mulher, Páscoa, Natal etc.)\nDay off no Natal, Ano Novo e aniversário\nIndicação premiada: R$ 300,00 no 6º mês + R$ 50,00 por mês por indicação ativa','WhatsApp (61) 8182-2325','clt','junior','presencial','Brasília','DF',2369.00,NULL,'assets/img/vagas/vaga49.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Consultor(a) de Venda Interna','Concluinte','A Concluinte (concluinte.com.br · @concluinteead) contrata consultor(a) de venda interna em Taguatinga Sul.','Experiência na área\nBoa comunicação verbal e escrita\nCriatividade','Salário de R$ 1.621,00\nComissão de até 20%\nBonificação mensal\nPremiação diária\nPassagens','WhatsApp (61) 98122-6097','clt','junior','presencial','Taguatinga','DF',1621.00,NULL,'assets/img/vagas/vaga50.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,8,'Atendente de Farmácia','Farmácia (rede em expansão)','Atendente de farmácia, escala 5x2. Empresa em processo de expansão, com oportunidades de crescimento interno.','Disponibilidade para fechamento\nBoa comunicação\nAtendimento ao público','Vale-alimentação\nVale-transporte\nPlano odontológico\nConvênio farmácia\nTelemedicina\nPlataforma de cursos\nParcerias com faculdades\nApoio psicológico\nAcompanhamento nutricional\nTrilha de carreira','(61) 99530-4348','clt','junior','presencial','Brasília','DF',NULL,NULL,'assets/img/vagas/vaga51.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Promotor de Vendas com Moto','Sama','Promotor com moto, CLT efetivo, início imediato. Segunda a sexta, das 7h às 16h48 (não trabalha sábado e domingo). Roteiro: São Sebastião, Itapoã, Lago Sul e Paranoá. Atividades: abastecimento, layout e precificação de produtos, controle de validade, organização de gôndolas e conquista de pontos extras. No WhatsApp, informe \"Promotor de Vendas\".','Residir no Paranoá, São Sebastião ou Itapoã\nEnsino médio completo\nMoto e CNH categoria A (documentação em dia)\nExperiência com abastecimento, precificação, organização e validade de produtos','Salário de R$ 1.658,80\nAdicional de periculosidade de R$ 497,00\nVale-refeição de R$ 31,00 por dia\nReembolso de R$ 0,65 por km\nAuxílio smartphone de R$ 100,00\nSeguro de vida em grupo','WhatsApp (61) 99127-7683','clt','junior','presencial','Paranoá','DF',1658.80,NULL,'assets/img/vagas/vaga52.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Operador de Caixa / Operador de Loja (temporário)','Sama','Ação Dia das Crianças – Ato II: contrato temporário de 29/09 a 15/10/2026 (17 dias, sendo 15 trabalhados), das 14h às 22h. Locais: Shopping Iguatemi, Taguatinga Shopping, Parque Shopping, Gilberto Salomão, SIA, Aeroporto e Águas Claras. Entrevista presencial na quinta-feira, 24/09, às 14h, na Agência Sama (EPNB, sentido Samambaia–Plano Piloto, em frente ao Costa Atacadista). Leve o currículo impresso.','Ser maior de 18 anos\nDisponibilidade das 14h às 22h\nExperiência com atendimento ao público\nInício imediato\nDisponibilidade para hora extra','Ganho total estimado de R$ 2.250,40 no período\nSalário do período de R$ 1.235,52 (base de R$ 2.180,33)\n13º, férias e 1/3 proporcionais\nVale-transporte de R$ 165,00\nVale-refeição de R$ 31,00/dia (R$ 465,00 no período)\nPossibilidade de horas extras','(61) 3386-4585','temporario','junior','presencial','Brasília','DF',2250.40,NULL,'assets/img/vagas/vaga53.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor Externo (Porta a Porta)','Fênix Telecom','15 vagas externas de vendedor porta a porta de pacotes de telefonia, banda larga e TV em Brasília e Águas Lindas. Somente moradores de Brasília e Águas Lindas. Falar com Fernanda ou André.','Boa comunicação\nExperiência na área\nProatividade','Salário de R$ 1.790,26\nVale-refeição de R$ 21,00/dia\nVale-transporte de R$ 11,00/dia\nComissões agressivas','WhatsApp (61) 99413-1811','clt','junior','presencial','Brasília','DF',1790.26,NULL,'assets/img/vagas/vaga54.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Atendente McDonald’s (Ceilândia)','McDonald’s (Grupo Levvo)','Novos horários no McDonald’s de Ceilândia: almoço, jantar e madrugada (11h45 às 21h, 14h às 23h ou 20h às 5h). Escala 5x2 ou 12x36.',NULL,'Salário de R$ 1.778,94\nPlano de saúde e odontológico\nTotalPass (desconto em academias)\nAuxílio cesta básica\nPlano de carreira\nPremiação por tempo de empresa\nDay off','WhatsApp (61) 99682-7682 · contrata@grupolevvo.com.br','clt','junior','presencial','Ceilândia','DF',1778.94,NULL,'assets/img/vagas/vaga55.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Serviços Gerais, Caixa, Cozinha, Pizzaria, Bar e Cumim','Don Romano Cantina & Pizzaria','Vagas: auxiliar de serviços gerais, operador de caixa, auxiliar de cozinha, auxiliar de pizzaria, auxiliar de bar e cumim. Unidades no Lago Sul, Águas Claras e Asa Norte. Envie o currículo com o nome da vaga pretendida.','Ser maior de 18 anos\nMorar no DF\nDisponibilidade de horário','Salário de R$ 1.750,68 + 5% de produtividade + gorjetas\nVale-transporte\nAlimentação no local\nAssistência médica e odontológica (sindicato)\nConvênio com Aqua Cerrado e SESC','selecaorestaurantelagosul@gmail.com · WhatsApp (61) 3968-6670','clt','junior','presencial','Lago Sul','DF',1750.68,NULL,'assets/img/vagas/vaga56.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Assistente de Vendas Online e E-commerce','Loja de e-commerce (Núcleo Bandeirante)','2 vagas, modelo híbrido (5 dias presenciais + 1 remoto) no Núcleo Bandeirante. Terça a sexta, das 9h às 18h, e sábado, das 9h às 13h. Entrevistas online. Atividades: atendimento e suporte às vendas online, gestão das redes sociais, anúncios em marketplaces (Mercado Livre e OLX), cadastro de produtos no ERP Bling, fotografia e edição básica de imagens, conferência dos anúncios e acompanhamento das vendas.','Experiência em vendas\nConhecimento básico de informática\nProatividade e vontade de aprender\nDiferencial: conhecimento ou experiência com o ERP Bling','Salário de R$ 1.800,00 + comissão','WhatsApp (61) 98264-9322 · https://w.app/gcy48w','clt','junior','hibrido','Núcleo Bandeirante','DF',1800.00,NULL,'assets/img/vagas/vaga57.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,17,'Auxiliar de Depósito','Santa Therezinha','Auxiliar de depósito, escala 5x2 (segunda a sexta). Candidatos de Ceilândia, Taguatinga ou Águas Lindas.',NULL,'Comissão por produtividade de até R$ 1.000\nVale-alimentação de R$ 25,00 por dia trabalhado\nConvênio com faculdades\nConvênio com o SESC\nPlano de saúde Hapvida\nBônus por qualidade e desempenho\nCesta básica\nPlano odontológico\nDescontos em academias\nTransporte da empresa\nPrograma de crescimento de carreira','WhatsApp (61) 99466-7123','clt','junior','presencial','Ceilândia','DF',NULL,NULL,'assets/img/vagas/vaga58.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Analista de Retenção (Cancelamento)','Indeniza Proteção Veicular','Atender clientes que pedem cancelamento, entender o motivo, negociar e apresentar alternativas para a permanência, com foco em reverter cancelamentos. Segunda a sexta, das 8h30 às 18h, em Taguatinga.','Comunicação e persuasão\nAgilidade e proatividade\nBoa negociação\nFoco em resultados\nSaber contornar objeções e resolver conflitos','Salário fixo\nVale-alimentação\nVale-transporte\nComissão por reversão','WhatsApp (61) 99367-6616','clt','junior','presencial','Taguatinga','DF',NULL,NULL,'assets/img/vagas/vaga59.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,6,'Operador de Cobrança','Santos Beneli Advogados','Operador de cobrança presencial em Brasília/DF, regime CLT. No assunto do e-mail, informe \"Operador de cobrança\".','Boa comunicação\nFoco em resultados\nVontade de crescer','Salário de R$ 1.744,75\nVale-transporte\nVale-alimentação\nConvênio com o SESC','rh@santosbeneli.com.br · WhatsApp (11) 94666-0470','clt','junior','presencial','Brasília','DF',1744.75,NULL,'assets/img/vagas/vaga60.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,16,'Auxiliar de Limpeza','Cantón Restaurante','O Cantón Restaurante (Peruvian Chinese Food) está aumentando o time e contrata auxiliar de limpeza no Venâncio Shopping, em Brasília. Escala 6x1.','Responsabilidade e comprometimento\nAgilidade\nGostar de trabalhar em equipe','Salário-base de R$ 1.750,00\n5% de produtividade\nComissão variável conforme as vendas do restaurante\nVale-transporte','WhatsApp (61) 99334-0848','clt','junior','presencial','Brasília','DF',1750.00,NULL,'assets/img/vagas/vaga78.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Auxiliar de Cozinha','Restaurante no Cruzeiro Novo','Vaga aberta para auxiliar de cozinha em loja no Cruzeiro Novo. Das 14h30 às 22h30, escala 5x2 com 2 folgas semanais. Atividades: auxílio no preparo, cocção, finalização e montagem; organização e limpeza da cozinha e das áreas de produção; apoio na lista de compras.','Comprometimento com o padrão da marca\nBoa comunicação\nTrabalho em equipe\nExperiência na área é um diferencial','Salário base de R$ 1.800,00\nBônus em dinheiro por metas alcançadas\nVale-transporte\nAlimentação no local\nAdicional noturno','WhatsApp (61) 99140-2285','clt','junior','presencial','Cruzeiro','DF',1800.00,NULL,'assets/img/vagas/vaga79.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Cozinheira(o)','Cozinha Industrial de Marmitas Saudáveis','Cozinha industrial especializada em marmitas saudáveis, com produção em Taguatinga Norte. Segunda a sexta, das 8h às 18h. Envie o currículo somente se morar em Taguatinga, Ceilândia, Samambaia, Riacho Fundo, Recanto das Emas ou Águas Lindas. No WhatsApp, use o assunto \"Cozinheira(o)\".','Experiência comprovada\nManipulação de alimentos\nHigiene e segurança\nOrganização\nLimpeza\nAgilidade','Remuneração de R$ 2.600,00','WhatsApp (61) 99379-0143','clt','pleno','presencial','Taguatinga','DF',2600.00,NULL,'assets/img/vagas/vaga80.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,16,'Auxiliar de Serviços Gerais','Grupo Bueno','Auxiliar de serviços gerais no Setor de Cargas (DF). Atividades: limpeza interna e externa do ambiente, descarte de lixo, preparo de café para funcionários e clientes da loja, higienização dos banheiros, uso de produtos de limpeza e zelo pela organização do espaço comum.','Conhecimento dos materiais de limpeza em geral\nExperiência como auxiliar de serviços gerais ou diarista é um diferencial','Salário de R$ 1.621,00 (CLT)\nVale-transporte\nVR/VA\nCesta básica\nPlano de saúde\nPlano odontológico\nWellhub (Gympass)\nStarbem\nConvênio com o SESC\nDesconto em peças\nProcessos seletivos internos','WhatsApp (61) 8458-0064','clt','junior','presencial','Brasília','DF',1621.00,NULL,'assets/img/vagas/vaga81.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Atendente McDonald’s (Taguatinga Centro)','McDonald’s Taguatinga Centro','Atendentes para o McDonald’s de Taguatinga Centro. Turnos disponíveis:\n• Diurno (6x1): 7h às 15h ou 10h às 18h\n• Noturno (6x1 e 5x2): 14h às 22h ou 23h, 15h às 23h ou 00h, 16h à 00h\n• Madrugada (5x2): 20h às 5h ou escala mista (2 dias noturno e 3 dias madrugada)','18 anos ou mais\nEnsino médio completo\nDisponibilidade para trabalhar em feriados e fins de semana','Plano de saúde\nPlano odontológico\nPlano de carreira\nSeguro de vida\nRefeição no local\nParceria com academias\nVale-transporte\nParticipação nos lucros','WhatsApp (61) 98487-2054','clt','junior','presencial','Taguatinga','DF',NULL,NULL,'assets/img/vagas/vaga82.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor(a)','Nação Fla Brasília','3 vagas para vendedor na loja da CLS 308, bloco D, loja 30, Asa Sul. Atividades: atendimento em vendas ágil e cordial, recebimento e conferência de mercadorias, reposição de mercadorias e organização do estoque.','Experiência na área','Salário de R$ 1.790,26\nComissão por meta\nVale-transporte','(61) 99847-9793','clt','junior','presencial','Asa Sul','DF',1790.26,NULL,'assets/img/vagas/vaga83.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,8,'Estágio em Enfermagem','Clínica em Taguatinga (cód. 1308)','Estágio em enfermagem (cód. 1308) em Taguatinga. Segunda a sexta, das 8h às 13h, e sábado, das 8h às 13h. Atividades: coleta de sangue, triagem de pacientes, apoio nos atendimentos de enfermagem e auxílio nas rotinas do setor.','Cursando Enfermagem a partir do 3º semestre\nResidir próximo à região de Taguatinga\nDisponibilidade para o horário informado','Bolsa-auxílio de R$ 750,00\nVale-transporte','WhatsApp (61) 99851-0917','estagio','estagiario','presencial','Taguatinga','DF',750.00,NULL,'assets/img/vagas/vaga84.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,16,'Camareiro(a)','Hotel Garden Norte','O Hotel Garden Norte tem vaga para camareiro(a). Escala 12x36, diurno ou noturno, com início imediato.','Habilidade na função igual ou similar\nNoção básica de informática\nOrganização e proatividade\nComprometimento','Ambiente organizado\nEquipe valorizada\nRespeito e confiança','hgempregos@gmail.com · WhatsApp (61) 99575-3710','clt','junior','presencial','Brasília','DF',NULL,NULL,'assets/img/vagas/vaga85.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,18,'Operador(a) de Loja','Sam’s Club Águas Claras','O Sam’s Club de Águas Claras contrata operador(a) de loja. Escala 6x1. Local: Rua Copaíba, s/n, LG 01, Mezanino 1B, Loja 2B – Águas Claras. Vagas limitadas.',NULL,'Salário de R$ 1.700,00\nVale-transporte\nAlimentação no local\nPlano de saúde\nPlano odontológico\nPLR – Participação nos Lucros e Resultados\nSeguro de vida\nConvênio com a Rede SESC\nTotalPass','silvanisidorio@gmail.com · WhatsApp (61) 99133-6108','clt','junior','presencial','Águas Claras','DF',1700.00,NULL,'assets/img/vagas/vaga86.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,15,'Auxiliar de Cozinha','Kairós Restaurante','Auxiliar de cozinha no Kairós Restaurante, em Águas Claras. Segunda a sábado, das 8h às 16h. Atividades: auxiliar na parte quente e nas saladas, verificar e auxiliar nas reposições do buffet, auxiliar no preparo de marmitas e na limpeza geral da cozinha. No WhatsApp, use o assunto \"Aux. cozinha\".','Ensino médio completo\nPreferencial: experiência com parte quente e saladas em restaurante','Salário de R$ 1.750,68\n5% de produtividade\nVale-transporte\nAlimentação no local','WhatsApp (61) 98289-3477','clt','junior','presencial','Águas Claras','DF',1750.68,NULL,'assets/img/vagas/vaga87.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Consultor de Vendas (Closer)','Mimória Business','Consultor de vendas (closer) na Asa Sul, Plano Piloto. Contratação PJ/MEI, de segunda a sexta, das 9h às 19h.','Ensino médio completo\nExperiência em vendas consultivas\nBoa comunicação\nHabilidade de negociação\nOrganização e foco em resultados\nDesejável: proatividade, persuasão, inteligência comercial, empatia, escuta ativa e compromisso com metas','Salário fixo de R$ 2.000,00\nComissão agressiva: possibilidade de chegar a R$ 5.000,00\nParticipação em plano de saúde/odontológico\nPlano de carreira','mimoriabusiness@gmail.com · (61) 98888-805','pj','junior','presencial','Asa Sul','DF',2000.00,5000.00,'assets/img/vagas/vaga88.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Consultora de Vendas','Viva Laser','Consultora de vendas em Brasília/DF, 44 horas semanais, das 9h às 19h. Atividades: atendimento presencial e por WhatsApp, acolhimento de clientes, conversão de avaliações, agendamentos, acompanhamento, fidelização, metas e indicadores. Envie currículo e Instagram pelo WhatsApp.','Comunicativa, persuasiva e comercial\nOrganizada, responsável e proativa\nExperiência com vendas será um diferencial','Salário de R$ 1.800,00 + comissão\nPossibilidade de ganhar R$ 3.000,00 ou mais\nVale-transporte\nVale-alimentação de R$ 27 por dia','WhatsApp (61) 99190-5286','clt','junior','presencial','Brasília','DF',1800.00,3000.00,'assets/img/vagas/vaga89.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Promotor de Vendas Exclusivo (com moto)','Prime Trade Marketing','Promotor de vendas exclusivo no Gama, período integral. Necessário ter moto. Atividades: organização e exposição de produtos, layout, envio diário de informações via WhatsApp e cumprimento de roteiro previamente definido.','Ter moto','Remuneração de R$ 2.112,73 (já com 30% de periculosidade)\nAjuda de custo\nVale-alimentação de R$ 25,00\nTotalPass\nDesconto em farmácia\nPAE (Programa de Assistência ao Empregado)','WhatsApp (61) 99281-5941','clt','junior','presencial','Gama','DF',2112.73,NULL,'assets/img/vagas/vaga90.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Promotor de Vendas','TIME Trade Marketing','Promotor de vendas no Gama, período integral (8h às 17h). Atividades: organização e exposição de produtos, layout, envio diário de informações, cumprimento de roteiro previamente definido e informações diárias via WhatsApp.',NULL,'Salário de R$ 1.625,18\nVale-transporte de acordo com a rota\nVale-alimentação de R$ 25,00\nTotalPass\nDesconto em farmácia\nPAE (Programa de Assistência ao Empregado)','WhatsApp (61) 99281-5941','clt','junior','presencial','Gama','DF',1625.18,NULL,'assets/img/vagas/vaga91.jpg','ativa',CURDATE());

INSERT INTO cursos(categoria_id,titulo,descricao,tipo,modalidade,nivel,duracao,gratuito,preco,url,imagem,instituicao) VALUES
(10,'Informática / Excel / Adm','Cursos 100% gratuitos com certificado.','curso','ead','iniciante','Variável',1,0,'https://www.ev.org.br','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
(11,'Empreendedorismo / Gestão','Capacitação para pequenos negócios e gestão empresarial.','curso','ead','iniciante','Variável',1,0,'https://www.sebrae.com.br','assets/img/cursos/capas/sebrae.jpg','SEBRAE'),
(12,'Administração / Atendimento / Saúde','Cursos online e gratuitos para desenvolvimento profissional.','curso','ead','iniciante','Variável',1,0,'https://www.escolavirtual.gov.br','assets/img/cursos/curso3.png','Escola Virtual.Gov (Enap)'),
(13,'Marketing Digital / Dados / UX','Cursos e ferramentas de aprendizagem para carreira digital.','curso','ead','iniciante','Variável',1,0,'https://grow.google/intl/pt/courses-and-tools/','assets/img/cursos/curso4.png','Google Grow'),
(14,'Negócios / Finanças / ESG','Cursos gratuitos e opções de formação em negócios.','curso','ead','intermediario','Variável',1,0,'https://cursosgratuitos.fgv.br/','assets/img/cursos/curso5.png','FGV Online');

-- Catálogo de capacitação: cursos e e-books gratuitos pesquisados em fontes oficiais (links conferidos).
-- Cada um com a sua imagem: capa real do e-book (assets/img/ebooks), imagem oficial do curso ou banner da instituição (assets/img/cursos).
-- A área é buscada pelo nome, então não depende da ordem dos ids.
INSERT INTO cursos(categoria_id,titulo,descricao,tipo,modalidade,nivel,duracao,gratuito,preco,url,imagem,instituicao) VALUES
((SELECT id FROM categorias WHERE nome='Administração e Atendimento' AND tipo='curso'),'Atendimento ao Público','Técnicas de atendimento e comunicação para o cliente se sentir valorizado no presencial, por telefone e on-line. Certificado digital gratuito.','curso','ead','iniciante','10 horas',1,NULL,'https://www.ev.org.br/cursos/atendimento-ao-publico','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Administração e Atendimento' AND tipo='curso'),'Comunicação Empresarial','Desenvolve a comunicação escrita e oral como diferencial no mercado de trabalho. Certificado digital gratuito.','curso','ead','iniciante','12 horas',1,NULL,'https://www.ev.org.br/cursos/comunicacao-empresarial','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Administração e Atendimento' AND tipo='curso'),'Noções básicas de atendimento ao cidadão','Atendimento humanizado e de qualidade, ética profissional e atendimento em diferentes canais. Aberto a qualquer pessoa, com certificado da Enap.','curso','ead','iniciante','20 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/1349','assets/img/cursos/capas/curso-nocoes-basicas-de-atendimento-ao-cidadao.jpg','Escola Virtual.Gov (Enap)'),
((SELECT id FROM categorias WHERE nome='Administração e Atendimento' AND tipo='curso'),'Cursos gratuitos presenciais do Senac DF','Editais de cursos gratuitos (Programa Senac de Gratuidade) em gestão, saúde, beleza, gastronomia e tecnologia, para pessoas com renda familiar de até 2 salários mínimos por pessoa.\nLocal: Distrito Federal (Taguatinga, Ceilândia, Gama, Santa Maria, Sobradinho e outras unidades).','curso','presencial','iniciante',NULL,1,NULL,'https://www.df.senac.br/curso-gratuito/','assets/img/cursos/capas/curso-senac-df-cursos-gratuitos-presenciais.jpg','SENAC'),
((SELECT id FROM categorias WHERE nome='Administração e Atendimento' AND tipo='curso'),'Liderança e Gestão de Equipes','Apresenta fundamentos de liderança, técnicas de trabalho em equipe e o clima organizacional como motor das equipes. Curso aberto a qualquer pessoa, com certificado.','curso','ead','intermediario','30 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/373','assets/img/cursos/capas/curso-lideranca-e-gestao-de-equipes.jpg','Escola Virtual.Gov (Enap)'),
((SELECT id FROM categorias WHERE nome='Administração e Atendimento' AND tipo='curso'),'Gestão de Conflitos e Negociação','Ensina a analisar e administrar conflitos no ambiente de trabalho e aplicar técnicas de negociação baseada em interesses. Curso aberto a qualquer pessoa, com certificado.','curso','ead','intermediario','20 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/372','assets/img/cursos/capas/curso-gestao-de-conflitos-e-negociacao.jpg','Escola Virtual.Gov (Enap)'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Como Conseguir um Novo Emprego','Ensina o passo a passo da busca de emprego: estratégias de procura de vagas, montagem do currículo, preparação para entrevista e criação do perfil no LinkedIn. Emite certificado digital com nota mínima de 70%.','curso','ead','iniciante','4 horas',1,NULL,'https://www.ev.org.br/cursos/Como-Conseguir-um-Novo-Emprego','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'IA para seu novo emprego: Do currículo à entrevista','Mostra como usar inteligência artificial (Microsoft Copilot) para extrair palavras-chave de vagas, otimizar currículo e LinkedIn e se preparar para entrevistas com o método STARR. Emite certificado digital com nota mínima de 70%.','curso','ead','iniciante','2 horas',1,NULL,'https://www.ev.org.br/cursos/iaempregos','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Desenvolvimento Profissional','Aborda planejamento de carreira, soft e hard skills, networking e aprendizagem contínua para entrar e se manter no mercado de trabalho. Emite certificado digital com nota mínima de 70%.','curso','ead','iniciante','8 horas',1,NULL,'https://www.ev.org.br/cursos/desenvolvimento-profissional','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Postura e Imagem Profissional','Trabalha imagem pessoal e profissional, postura, convívio social e cultura organizacional no ambiente de trabalho. Emite certificado digital com nota mínima de 70%.','curso','ead','iniciante','8 horas',1,NULL,'https://www.ev.org.br/cursos/postura-e-imagem-profissional','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Inteligência Emocional','Desenvolve a gestão das próprias emoções e das relações interpessoais, a construção de um ambiente de trabalho positivo e a liderança positiva. Curso aberto a qualquer pessoa, com certificado.','curso','ead','iniciante','50 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/318','assets/img/cursos/capas/curso-inteligencia-emocional.jpg','Escola Virtual.Gov (Enap)'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Comunicação Não Violenta','Ensina os quatro componentes da CNV (observar, sentir, reconhecer necessidades e pedir) para uma comunicação mais empática e assertiva no trabalho e na vida pessoal. Curso aberto, com certificado.','curso','ead','iniciante','20 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/463','assets/img/cursos/capas/curso-comunicacao-nao-violenta.jpg','Escola Virtual.Gov (Enap)'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Comunicação Assertiva: Oratória, Retórica e Técnicas de Apresentação','Aborda comunicação assertiva, oratória, linguagem corporal, como superar o medo de falar em público e técnicas de apresentação. Curso aberto, com certificado.','curso','ead','iniciante','50 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/1347','assets/img/cursos/capas/curso-comunicacao-assertiva-oratoria-retorica-e-tecnicas-de-aprese.jpg','Escola Virtual.Gov (Enap)'),
((SELECT id FROM categorias WHERE nome='Empreendedorismo e Gestão' AND tipo='curso'),'Aprender a empreender','Características do empreendedor, pesquisa de mercado, marketing, vendas e noções de finanças e fluxo de caixa para quem quer abrir ou melhorar um negócio.','curso','ead','iniciante','16 horas',1,NULL,'https://loja.sebrae.com.br/aprender-a-empreender-1-372000001028','assets/img/cursos/capas/curso-aprender-a-empreender.jpg','SEBRAE'),
((SELECT id FROM categorias WHERE nome='Empreendedorismo e Gestão' AND tipo='curso'),'Gestão de Equipe de Vendas','Apresenta liderança, comunicação, motivação, indicadores de desempenho e capacitação contínua de equipes de vendas em micro e pequenas empresas. Curso online gratuito.','curso','ead','iniciante','5 horas',1,NULL,'https://loja.sebrae.com.br/gest-o-de-equipe-de-vendas-1-372000026923','assets/img/cursos/capas/curso-gestao-de-equipe-de-vendas.jpg','SEBRAE'),
((SELECT id FROM categorias WHERE nome='Empreendedorismo e Gestão' AND tipo='curso'),'Como se tornar um microempreendedor individual','Explica o que é ser MEI, vantagens, direitos e deveres, o passo a passo da formalização e como se proteger de fraudes. Curso online gratuito com certificado.','curso','ead','iniciante','10 horas',1,NULL,'https://loja.sebrae.com.br/como-se-tornar-um-microempreendedor-individual-1-371440103451','assets/img/cursos/capas/curso-como-se-tornar-um-microempreendedor-individual.jpg','SEBRAE'),
((SELECT id FROM categorias WHERE nome='Informática e Excel' AND tipo='curso'),'Microsoft Excel 2016 - Básico','Formatação de planilhas e gráficos, classificação de dados e uso de fórmulas e funções para quem está começando no Excel. Certificado digital gratuito após aprovação.','curso','ead','iniciante','15 horas',1,NULL,'https://www.ev.org.br/cursos/microsoft-excel-2016-basico','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Informática e Excel' AND tipo='curso'),'Excel na Prática','Criação de planilhas eficientes, análise de dados e automação de tarefas no Excel, com aplicação no trabalho e na organização financeira pessoal. Certificado digital gratuito.','curso','ead','iniciante','16 horas',1,NULL,'https://www.ev.org.br/cursos/excel-na-pratica','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Informática e Excel' AND tipo='curso'),'Excel Avançado','Fórmulas complexas, validação de dados, tabelas dinâmicas, formulários, banco de dados e automação com macros e VBA. Aberto a qualquer pessoa, com certificado da Enap.','curso','ead','avancado','30 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/1274','assets/img/cursos/capas/curso-excel-avancado.jpg','Escola Virtual.Gov (Enap)'),
((SELECT id FROM categorias WHERE nome='Informática e Excel' AND tipo='curso'),'Cursos FIC gratuitos do IFB – Campus Brasília','Cursos rápidos de Formação Inicial e Continuada (FIC), gratuitos e presenciais, com editais ao longo do ano (ex.: aplicações de IA, inglês, desenvolvimento de aplicativos e Libras).\nLocal: Brasília/DF (Asa Norte).','curso','presencial','iniciante',NULL,1,NULL,'https://www.ifb.edu.br/93-concursos/cursos-fic','assets/img/cursos/capas/curso-ifb-cursos-fic-gratuitos.jpg','IFB – Instituto Federal de Brasília'),
((SELECT id FROM categorias WHERE nome='Marketing, Dados e UX' AND tipo='curso'),'Princípios do marketing digital','Noções básicas de marketing digital para descobrir novas oportunidades de carreira e de negócio. Certificado do Google.','curso','ead','iniciante',NULL,1,NULL,'https://skillshop.exceedlms.com/student/collection/1830706?locale=pt-PT','assets/img/cursos/curso4.png','Google (Grow with Google)'),
((SELECT id FROM categorias WHERE nome='Marketing, Dados e UX' AND tipo='curso'),'Introdução à Ciência de Dados - Conceitos e Ferramentas','Primeiros passos em ciência de dados: papel do cientista de dados, BI, preparação de dados e aprendizado de máquina, com prática na ferramenta KNIME. Certificado da Enap.','curso','ead','intermediario','4 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/976','assets/img/cursos/capas/curso-introducao-a-ciencia-de-dados-conceitos-e-ferramentas.jpg','Escola Virtual.Gov (Enap)'),
((SELECT id FROM categorias WHERE nome='Marketing, Dados e UX' AND tipo='curso'),'Aplicação do Power BI para Aprimoramento da Gestão','Ensina a usar o Power BI para obter e tratar dados, modelar, fazer cálculos, montar visualizações e publicar dashboards. Curso aberto com certificado da Enap.','curso','ead','intermediario','25 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/840','assets/img/cursos/capas/curso-aplicacao-do-power-bi-para-aprimoramento-da-gestao.jpg','Escola Virtual.Gov (Enap)'),
((SELECT id FROM categorias WHERE nome='Negócios, Finanças e ESG' AND tipo='curso'),'Educação Financeira','Perfil financeiro, controle de gastos, noções de investimento e sustentabilidade para organizar o dinheiro. Certificado digital gratuito.','curso','ead','iniciante','4 horas',1,NULL,'https://www.ev.org.br/cursos/educacao-financeira','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Negócios, Finanças e ESG' AND tipo='curso'),'ESG para pequenas empresas','Conceitos de ESG (ambiental, social e governança) e práticas simples para integrar sustentabilidade à gestão de pequenos negócios.','curso','ead','iniciante','15 horas',1,NULL,'https://loja.sebrae.com.br/esg-para-pequenas-empresas-1-372000054844','assets/img/cursos/capas/curso-esg-para-pequenas-empresas.jpg','SEBRAE'),
((SELECT id FROM categorias WHERE nome='Negócios, Finanças e ESG' AND tipo='curso'),'Como organizar o orçamento familiar','Ferramentas para identificar gastos, planejar receitas e evitar o endividamento. Autoinstrucional, com declaração de conclusão.','curso','ead','iniciante',NULL,1,NULL,'https://cursosgratuitos.fgv.br/curso/como-organizar-o-orcamento-familiar','assets/img/cursos/curso5.png','FGV Online'),
((SELECT id FROM categorias WHERE nome='Negócios, Finanças e ESG' AND tipo='curso'),'Como planejar a aposentadoria','Visão de longo prazo sobre previdência pública e privada e estratégias de poupança. Autoinstrucional, com declaração de conclusão.','curso','ead','iniciante',NULL,1,NULL,'https://cursosgratuitos.fgv.br/curso/como-planejar-a-aposentadoria','assets/img/cursos/curso5.png','FGV Online'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Introdução aos conceitos de IA','Módulo gratuito com os conceitos básicos de inteligência artificial e como ela aparece no dia a dia do trabalho.','curso','ead','iniciante',NULL,1,NULL,'https://learn.microsoft.com/pt-br/training/modules/get-started-ai-fundamentals/','assets/img/cursos/capas/curso-introducao-aos-conceitos-de-ia.jpg','Microsoft Learn'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Inteligência Artificial Generativa','Explica o que é IA generativa, como ela difere da IA tradicional, geração de texto e de imagens e o impacto no mercado de trabalho. Curso aberto com certificado da Enap.','curso','ead','iniciante','2 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/1091','assets/img/cursos/capas/curso-inteligencia-artificial-generativa.jpg','Escola Virtual.Gov (Enap) (conteúdo Microsoft)'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'IA Generativo da Microsoft - Copilot','Mostra como usar o Copilot no dia a dia de trabalho, integrado ao Bing, Teams, Outlook, Word, PowerPoint e Excel. Curso aberto com certificado da Enap.','curso','ead','iniciante','2 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/1167','assets/img/cursos/capas/curso-ia-generativo-da-microsoft-copilot.jpg','Escola Virtual.Gov (Enap) (conteúdo Microsoft)'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Ética em IA','Aborda os dilemas éticos da inteligência artificial, os princípios de IA responsável e o uso ético da IA generativa. Curso aberto com certificado da Enap.','curso','ead','iniciante','2 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/1090','assets/img/cursos/capas/curso-etica-em-ia.jpg','Escola Virtual.Gov (Enap) (conteúdo Microsoft)'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Inteligência Artificial para simplificar o dia a dia','Ensina a usar IA em tarefas criativas e do cotidiano, com modelos de geração de texto (GPT) e ferramentas de geração de imagem. Curso aberto com certificado da Enap.','curso','ead','iniciante','4 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/861','assets/img/cursos/capas/curso-inteligencia-artificial-para-simplificar-o-dia-a-dia.jpg','Escola Virtual.Gov (Enap)'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Introdução à IA gerativa e aos agentes','Módulo que apresenta os conceitos de IA generativa, como funcionam os grandes modelos de linguagem (LLMs), como escrever bons prompts e o que são agentes de IA. Não emite certificado, mas registra a conclusão e a avaliação no perfil do Microsoft Learn.','curso','ead','iniciante',NULL,1,NULL,'https://learn.microsoft.com/pt-br/training/modules/fundamentals-generative-ai/','assets/img/cursos/capas/curso-introducao-a-ia-gerativa-e-aos-agentes.jpg','Microsoft Learn'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Linguagem de Programação Python - Básico','Ensina lógica de programação e os fundamentos da linguagem Python, com estruturas lógicas e funções. Dá certificado digital a quem tirar 70% ou mais na avaliação final (idade mínima: 16 anos).','curso','ead','iniciante','18 horas',1,NULL,'https://www.ev.org.br/cursos/linguagem-de-programacao-python-basico','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Crie um site simples usando HTML, CSS e JavaScript','Introdução ao desenvolvimento web: instalação do Visual Studio Code e criação de uma página com HTML, estilo com CSS e interatividade com JavaScript. Dá certificado digital a quem for aprovado.','curso','ead','iniciante','2 horas',1,NULL,'https://www.ev.org.br/cursos/crie-um-site-simples-usando-html-css-e-javascript','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual (conteúdo Microsoft)'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Fundamentos de TI: Hardware e Software','Apresenta os conceitos básicos de computação, os componentes do computador, sistemas operacionais e noções de prevenção e segurança. Bom ponto de partida para suporte de TI, com certificado digital para quem for aprovado.','curso','ead','iniciante','7 horas',1,NULL,'https://www.ev.org.br/cursos/fundamentos-de-ti-hardware-e-software','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Segurança da Informação para Todos','Ensina práticas de segurança digital: privacidade e proteção de dados, códigos maliciosos, proteção de dispositivos e trabalho remoto seguro. Curso aberto com certificado da Enap.','curso','ead','iniciante','24 horas',1,NULL,'https://www.escolavirtual.gov.br/curso/1256','assets/img/cursos/capas/curso-seguranca-da-informacao-para-todos.jpg','Escola Virtual.Gov (Enap) (conteúdo da SGD e da ESR/RNP)'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Descrever a computação em nuvem','Módulo que apresenta a computação em nuvem: modelos de nuvem pública, privada e híbrida, responsabilidade compartilhada e cobrança por consumo. Não emite certificado, mas registra a conclusão no perfil do Microsoft Learn.','curso','ead','iniciante',NULL,1,NULL,'https://learn.microsoft.com/pt-br/training/modules/describe-cloud-compute/','assets/img/cursos/capas/curso-descrever-a-computacao-em-nuvem.jpg','Microsoft Learn'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Guia para elaborar seu currículo e carta de apresentação','E-book em PDF com orientações para montar o currículo e escrever uma carta de apresentação.','ebook','ead','iniciante',NULL,1,NULL,'https://www.idp.edu.br/arquivos/mestrados-doutorados/e-book-guia-para-elaborar-seu-curriculo-e-carta-de-apresentacao.pdf','assets/img/ebooks/ebook-guia-para-elaborar-seu-curriculo-e-carta-de-apresentacao.jpg','IDP – Instituto Brasileiro de Ensino, Desenvolvimento e Pesquisa'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Cartilha Digital: Conhecendo os direitos do trabalhador','Cartilha em PDF que explica, em linguagem simples, os principais direitos de quem trabalha com carteira assinada.','ebook','ead','iniciante',NULL,1,NULL,'https://educapes.capes.gov.br/bitstream/capes/603856/2/Cartilha%20Digital%20-%20Conhecendo%20os%20direitos%20do%20trabalhador%20%282%29%20%281%29.pdf','assets/img/ebooks/ebook-cartilha-digital-conhecendo-os-direitos-do-trabalhador.jpg','eduCAPES'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Passo a passo da Carteira de Trabalho Digital','Guia oficial em PDF para acessar e usar a Carteira de Trabalho Digital pelo aplicativo e pela web.','ebook','ead','iniciante',NULL,1,NULL,'https://www.gov.br/trabalho-e-emprego/pt-br/servicos/trabalhador/carteira-de-trabalho/Passo_a_Passo_CTPSDigital_APP_e_WEB.pdf','assets/img/ebooks/ebook-passo-a-passo-da-carteira-de-trabalho-digital.jpg','Ministério do Trabalho e Emprego'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Manual da Aprendizagem Profissional','Manual oficial (edição 2024) com perguntas e respostas sobre o programa Jovem Aprendiz: quem pode participar, direitos e como funciona a contratação.','ebook','ead','iniciante',NULL,1,NULL,'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/escola/e-biblioteca/manual-de-aprendizagem-profissional.pdf','assets/img/ebooks/ebook-manual-da-aprendizagem-profissional.jpg','Ministério do Trabalho e Emprego'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Cartilha - Oficina para elaboração de currículo e preparação para entrevista de emprego','Cartilha voltada a jovens que buscam emprego, com orientações para montar o currículo e se preparar para a entrevista.','ebook','ead','iniciante',NULL,1,NULL,'https://educapes.capes.gov.br/handle/capes/560895','assets/img/ebooks/ebook-cartilha-oficina-para-elaboracao-de-curriculo-e-preparacao-p.jpg','IFRN (Instituto Federal do Rio Grande do Norte) / eduCAPES'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Guia do Primeiro Emprego','Guia para quem vai entrar no mercado de trabalho: como organizar a documentação, montar o currículo e participar de processos seletivos.','ebook','ead','iniciante',NULL,1,NULL,'https://reciclar.org.br/downloads/Guia-do-primeiro-emprego.pdf','assets/img/ebooks/ebook-guia-do-primeiro-emprego.jpg','Instituto Reciclar'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Dicas de Empregabilidade','Cartilha sobre como preparar o currículo, onde procurar vagas de emprego e como se preparar para a entrevista. Foi feita para migrantes, mas as dicas servem para qualquer pessoa em busca de emprego no Brasil.','ebook','ead','iniciante',NULL,1,NULL,'https://migrantes.paginas.ufsc.br/files/2020/10/Portugu%C3%AAs-Cartilha-Empregabilidade.pdf','assets/img/ebooks/ebook-dicas-de-empregabilidade.jpg','Projeto Integra / UFSC (Universidade Federal de Santa Catarina)'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Saiba como atrair recrutadores para o seu LinkedIn','E-book com dicas para montar um perfil no LinkedIn que chame a atenção de recrutadores e para usar a rede para fazer contatos e encontrar oportunidades.','ebook','ead','iniciante',NULL,1,NULL,'https://www.ucs.br/site/midia/arquivos/ebook-dicas-linkedin.pdf','assets/img/ebooks/ebook-saiba-como-atrair-recrutadores-para-o-seu-linkedin.jpg','UCS (Universidade de Caxias do Sul)'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Nova Cartilha Esclarecedora sobre a Lei do Estágio (Lei 11.788/2008)','Perguntas e respostas sobre a Lei do Estágio: jornada, bolsa, recesso, seguro, duração do contrato e o papel da escola e da empresa.','ebook','ead','iniciante',NULL,1,NULL,'https://www.gov.br/hubrasil/pt-br/hospitais-universitarios/regiao-nordeste/hc-ufpe/ensino-e-pesquisa/site-antigo-ate-31-01-2024/setor-de-gestao-do-ensino/graduacao/estagio-curricular/cartilha-esclarecedora-sobre-a-lei-do-estagio.pdf','assets/img/ebooks/ebook-nova-cartilha-esclarecedora-sobre-a-lei-do-estagio-lei-11-78.jpg','Ministério do Trabalho e Emprego (MTE)'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Cartilha - O Trabalho por Plataformas Digitais: o trabalhador por aplicativo tem direitos?','Explica os direitos de quem trabalha por aplicativos (entregas, transporte e outros) e onde buscar ajuda em caso de problemas.','ebook','ead','iniciante',NULL,1,NULL,'https://www.tst.jus.br/documents/1199940/0/13.12.2021+-+Cartilha_trabalho_app_MPT_online.pdf/31f1165c-41ee-975a-bccd-43fd58518c15?t=1639784077416','assets/img/ebooks/ebook-cartilha-o-trabalho-por-plataformas-digitais-o-trabalhador-p.jpg','TRT da 2ª Região e Ministério Público do Trabalho (CONAFRET/MPT), publicada no portal do TST'),
((SELECT id FROM categorias WHERE nome='Carreira e Empregabilidade' AND tipo='curso'),'Trabalhadores Domésticos: Direitos e Deveres','Cartilha sobre os direitos e deveres de empregados domésticos e as obrigações do empregador, de acordo com a Lei Complementar nº 150/2015.','ebook','ead','iniciante',NULL,1,NULL,'https://www.gov.br/esocial/pt-br/documentacao-tecnica/manuais/cartilha-trabalhadores-domesticos-direitos-e-deveres','assets/img/ebooks/ebook-trabalhadores-domesticos-direitos-e-deveres.jpg','Ministério do Trabalho e Previdência Social / Portal eSocial (gov.br)'),
((SELECT id FROM categorias WHERE nome='Empreendedorismo e Gestão' AND tipo='curso'),'Gestão de Pessoas (apostila do curso)','Apostila sobre gestão de pessoas em pequenas empresas: recrutamento e seleção, desenvolvimento e retenção de profissionais e liderança de equipes.','ebook','ead','iniciante',NULL,1,NULL,'https://eadlms.sebrae.com.br/courses/novo-sebrae/gtpe18/pdf/apostila_gp.pdf','assets/img/ebooks/ebook-gestao-de-pessoas-apostila-do-curso.jpg','SEBRAE'),
((SELECT id FROM categorias WHERE nome='Negócios, Finanças e ESG' AND tipo='curso'),'Caderno de Educação Financeira – Gestão de Finanças Pessoais','Livro digital gratuito do Banco Central sobre como planejar o orçamento, usar crédito com consciência, poupar e investir.','ebook','ead','iniciante',NULL,1,NULL,'https://www.bcb.gov.br/content/cidadaniafinanceira/documentos_cidadania/Cuidando_do_seu_dinheiro_Gestao_de_Financas_Pessoais/caderno_cidadania_financeira.pdf','assets/img/ebooks/ebook-caderno-de-educacao-financeira-gestao-de-financas-pessoais.jpg','Banco Central do Brasil'),
((SELECT id FROM categorias WHERE nome='Negócios, Finanças e ESG' AND tipo='curso'),'Orçamento Pessoal ou Familiar (Caderno de Educação Financeira – Módulo 2)','Módulo em PDF do Banco Central, edição 2026, com o passo a passo para montar e acompanhar o orçamento pessoal ou da família.','ebook','ead','iniciante',NULL,1,NULL,'https://www.bcb.gov.br/content/cidadaniafinanceira/documentos_cidadania/Cuidando_do_seu_dinheiro_Gestao_de_Financas_Pessoais/v4_modulo_2_caderno_educacao_financeira_430206_2026.pdf','assets/img/ebooks/ebook-orcamento-pessoal-ou-familiar-caderno-de-educacao-financeira.jpg','Banco Central do Brasil'),
((SELECT id FROM categorias WHERE nome='Negócios, Finanças e ESG' AND tipo='curso'),'Guia CVM de Planejamento Financeiro','Guia curto sobre planejamento financeiro pessoal e familiar: como organizar o orçamento doméstico, definir objetivos e se preparar para a aposentadoria.','ebook','ead','iniciante',NULL,1,NULL,'https://www.gov.br/investidor/pt-br/educacional/publicacoes-educacionais/guias/guia-de-planejamento-financeiro/guia-planejamento-financeiro.pdf/@@download/file','assets/img/ebooks/ebook-guia-cvm-de-planejamento-financeiro.jpg','CVM – Portal do Investidor'),
((SELECT id FROM categorias WHERE nome='Negócios, Finanças e ESG' AND tipo='curso'),'Como sair das dívidas em 10 passos','Guia em 10 passos para quem tem dívidas: fazer o diagnóstico, negociar com os credores e reorganizar o orçamento.','ebook','ead','iniciante',NULL,1,NULL,'https://meubolsoemdia.com.br/pdf/Ebook-Como-Sair-das-Dividas-em-10-Passos-ebook.pdf','assets/img/ebooks/ebook-como-sair-das-dividas-em-10-passos.jpg','Febraban – Meu Bolso em Dia'),
((SELECT id FROM categorias WHERE nome='Negócios, Finanças e ESG' AND tipo='curso'),'Guia da Renda Extra','Apresenta ideias e formas de conseguir uma renda extra para completar o orçamento, sair do endividamento e começar a poupar.','ebook','ead','iniciante',NULL,1,NULL,'https://meubolsoemdia.com.br/pdf/ebook-renda-extra.pdf','assets/img/ebooks/ebook-guia-da-renda-extra.jpg','Febraban – Meu Bolso em Dia'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Inteligência Artificial 2025','Apostila introdutória sobre inteligência artificial: conceitos básicos, história, principais empresas e ferramentas, usos no trabalho, benefícios e questões éticas.','ebook','ead','iniciante',NULL,1,NULL,'https://esesp.es.gov.br/Media/Apostilas/2025/Apostila_Trilha_Inovacao/Apostila%20-%20Intelig%C3%AAncia%20Artificial.pdf','assets/img/ebooks/ebook-inteligencia-artificial-2025.jpg','Esesp (Escola de Serviço Público do Espírito Santo) / Governo do Estado do Espírito Santo'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Guia de Inteligência Artificial Aplicada para Profissões','E-book de 2025 com explicações e exemplos práticos de uso da IA em diferentes profissões, incluindo ferramentas gratuitas para iniciantes, com os limites e cuidados éticos de cada uso.','ebook','ead','iniciante',NULL,1,NULL,'https://labtec.ufsc.br/ebooks/PDF/Guia%20de%20Intelig%C3%AAncia%20Artificial%20Aplicada%20para%20Profiss%C3%B5es.pdf','assets/img/ebooks/ebook-guia-de-inteligencia-artificial-aplicada-para-profissoes.jpg','UFSC (Universidade Federal de Santa Catarina) - PPGTIC/Labtec'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Fascículo Inteligência Artificial - Cartilha de Segurança para Internet','Fascículo curto sobre como usar ferramentas de IA com segurança: limitações dos modelos de linguagem, como conferir as respostas e cuidados com dados pessoais nos prompts.','ebook','ead','iniciante',NULL,1,NULL,'https://cartilha.cert.br/fasciculos/ia/fasciculo-ia.pdf','assets/img/ebooks/ebook-fasciculo-inteligencia-artificial-cartilha-de-seguranca-para.jpg','CERT.br / NIC.br'),
((SELECT id FROM categorias WHERE nome='Tecnologia e Inteligência Artificial' AND tipo='curso'),'Fascículo Golpes: Evite Fraudes - Cartilha de Segurança para Internet','Dicas práticas para reconhecer e evitar golpes na internet, proteger contas com senhas fortes e verificação em duas etapas e conferir contatos antes de pagar ou transferir.','ebook','ead','iniciante',NULL,1,NULL,'https://cartilha.cert.br/fasciculos/golpes-evite-fraudes/fasciculo-golpes-evite-fraudes.pdf','assets/img/ebooks/ebook-fasciculo-golpes-evite-fraudes-cartilha-de-seguranca-para-in.jpg','CERT.br / NIC.br');

INSERT INTO assinaturas(usuario_id,plano,valor,data_inicio,data_fim,status) VALUES
(3,'assinante',9.90,CURDATE(),DATE_ADD(CURDATE(), INTERVAL 30 DAY),'ativa');
