@startuml
!include estilo.iuml
mainframe uc Realizar login
left to right direction
actor Candidato
actor Empresa
actor Administrador
rectangle "Conecta Vagas DF" {
  usecase "Realizar login" as L
  usecase "Pausar o login após\ntentativas repetidas" as B
  usecase "Encerrar sessão\n(sair)" as S
}
actor Sistema
Candidato -- L
Empresa -- L
Administrador -- L
Candidato -- S
Empresa -- S
Administrador -- S
L <.. B : <<extend>>
B -- Sistema
@enduml
