@startuml
!include estilo.iuml
mainframe uc Consultas públicas
left to right direction
actor Candidato as C
rectangle "Conecta Vagas DF" {
  usecase "Consultar vagas\n(busca e filtros)" as CV
  usecase "Visualizar detalhe\nda vaga" as DV
  usecase "Exibir nota de match" as NM
  usecase "Consultar cursos\ne e-books" as CC
  usecase "Visualizar detalhe\ndo curso" as DC
  usecase "Baixar o PDF da\nbiblioteca" as BP
}
C -- CV
C -- CC
CV <.. DV : <<extend>>
DV <.. NM : <<extend>>
CC <.. DC : <<extend>>
DC <.. BP : <<extend>>
actor Sistema as SI
NM -- SI
@enduml
