@startuml
!include estilo.iuml
mainframe uc Manter usuário
left to right direction
actor Administrador as A
rectangle "Conecta Vagas DF" {
  usecase "Cadastrar usuário" as C
  usecase "Alterar usuário" as U
  usecase "Ativar / desativar\nusuário" as T
  usecase "Excluir usuário" as E
}
A -- C
A -- U
A -- T
A -- E
@enduml
